#!/bin/bash

set -x

if [ ! -d $OPENSHIFT_DATA_DIR/gradle-2.7 ]
        then
                cd $OPENSHIFT_DATA_DIR
                wget https://services.gradle.org/distributions/gradle-2.7-bin.zip
                unzip gradle-2.7-bin.zip
                rm -f gradle-2.7-bin.zip
fi

if [ ! -d $OPENSHIFT_DATA_DIR/gradle ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir gradle
fi

if [ ! -d $OPENSHIFT_DATA_DIR/logs ]
        then
                cd $OPENSHIFT_DATA_DIR
				mkdir logs
fi

cd $OPENSHIFT_REPO_DIR
export GRADLE_USER_HOME=$OPENSHIFT_DATA_DIR/gradle
export GRADLE_HOME=$OPENSHIFT_DATA_DIR/gradle-2.7
export GRADLE_OPTS="-Xms384m -Xmx412m"
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$GRADLE_HOME/bin:$PATH

gradle bootRepackage
